### ISSUE TITLE
Missing dependencies in esp-html-skeleton

### ISSUE THREAD

**Issue by SimonVleugels** [embedthis/esp#84]
When running `pak install esp-html-skeleton`
```    
[Info] Search catalog: "pak" for esp-html-skeleton for version ~*
[Cache] esp-html-skeleton 5.5.1
[Mkdir] /home/simon/.paks/esp-html-skeleton/embedthis/5.5.1
[Get] https://github.com/embedthis/esp-html-skeleton/archive/v5.5.1.tar.gz
[Extract] Extract to /home/simon/.paks/esp-html-skeleton/embedthis/5.5.1
[Info] Search catalog: "pak" for esp-mvc for version ~5.5
[Cache] esp-mvc 5.5.2
[Mkdir] /home/simon/.paks/esp-mvc/embedthis/5.5.2
[Get] https://github.com/embedthis/esp-mvc/archive/v5.5.2.tar.gz
[Extract] Extract to /home/simon/.paks/esp-mvc/embedthis/5.5.2
[Info] Search catalog: "pak" for exp-canon for version ~0.3
[Info] Search catalog: "bower" for exp-canon for version ~0.3
[Info] Search catalog: "npm" for exp-canon for version ~0.3
Cannot locate package "exp-canon" ~0.3
Cannot cache esp-mvc because of missing required dependency "exp-canon"
pak: ERROR: Cannot cache esp-html-skeleton because of missing required dependency "esp-mvc"
```

**Comment by kasikoliu** [comment]
I have the same trouble as you have.
I use  makeme tool built them with default settings.

ESP version: 7.0.2,  built from source 
MakeMe version:0.10.8
Pak Version;0.12.4
O/S: Linux Ubuntu 16.04.4 LTS

> root@ubuntuinit-virtual-machine:~/web/demo# pak install esp-html-skeleton
      [Info] Search catalog: "pak" for esp-html-skeleton for version ~*
     [Cache] esp-html-skeleton 5.5.1
     [Mkdir] /root/.paks/esp-html-skeleton/embedthis/5.5.1
       [Get] https://github.com/embedthis/esp-html-skeleton/archive/v5.5.1.tar.gz
   [Extract] Extract to /root/.paks/esp-html-skeleton/embedthis/5.5.1
      [Info] Search catalog: "pak" for esp-mvc for version ~5.5
     [Cache] esp-mvc 5.5.2
     [Mkdir] /root/.paks/esp-mvc/embedthis/5.5.2
       [Get] https://github.com/embedthis/esp-mvc/archive/v5.5.2.tar.gz
   [Extract] Extract to /root/.paks/esp-mvc/embedthis/5.5.2
      [Info] Search catalog: "pak" for exp-js for version ~0.3
     [Cache] exp-js 0.3.2
     [Mkdir] /root/.paks/exp-js/embedthis/0.3.2
       [Get] https://github.com/embedthis/exp-js/archive/v0.3.2.tar.gz
   [Extract] Extract to /root/.paks/exp-js/embedthis/0.3.2
      [Info] exp-js 0.3.2 successfully cached
      [Info] Search catalog: "pak" for exp-less for version ~0.3
     [Cache] exp-less 0.3.0
     [Mkdir] /root/.paks/exp-less/embedthis/0.3.0
       [Get] https://github.com/embedthis/exp-less/archive/v0.3.0.tar.gz
   [Extract] Extract to /root/.paks/exp-less/embedthis/0.3.0
      [Info] exp-less 0.3.0 successfully cached
      [Info] Search catalog: "pak" for exp-css for version ~0.3
     [Cache] exp-css 0.3.1
     [Mkdir] /root/.paks/exp-css/embedthis/0.3.1
       [Get] https://github.com/embedthis/exp-css/archive/v0.3.1.tar.gz
   [Extract] Extract to /root/.paks/exp-css/embedthis/0.3.1
      [Info] exp-css 0.3.1 successfully cached
      [Info] Search catalog: "pak" for exp-esp for version ~0.3
     [Cache] exp-esp 0.3.1
     [Mkdir] /root/.paks/exp-esp/embedthis/0.3.1
       [Get] https://github.com/embedthis/exp-esp/archive/v0.3.1.tar.gz
   [Extract] Extract to /root/.paks/exp-esp/embedthis/0.3.1
      [Info] exp-esp 0.3.1 successfully cached
      [Info] Search catalog: "pak" for exp-html for version ~0.2
     [Cache] exp-html 0.2.0
     [Mkdir] /root/.paks/exp-html/embedthis/0.2.0
       [Get] https://github.com/embedthis/exp-html/archive/v0.2.0.tar.gz
   [Extract] Extract to /root/.paks/exp-html/embedthis/0.2.0
      [Info] exp-html 0.1.1 successfully cached
      [Info] Search catalog: "pak" for exp-canon for version ~0.3
      [Info] Search catalog: "bower" for exp-canon for version ~0.3
      [Info] Search catalog: "npm" for exp-canon for version ~0.3
Cannot locate package "exp-canon" ~0.3
Cannot cache esp-mvc because of missing required dependency "exp-canon"
pak: ERROR: Cannot cache esp-html-skeleton because of missing required dependency "esp-mvc"

**Comment by mobrien** [comment]
Should be fixed now.
