### ISSUE TITLE
User is not recognized as authenticated 

### ISSUE THREAD

**Issue by CristianIonutIonescu** [embedthis/esp#91]
Hello,

Unfortunately, I stumbled across another bug.
If the authentication store is defined as "app" the esp doesn't recognize the user as being authenticated even if the authentication is successful.

###  Environment
ESP version: 8.0.2 build from source
O/S: Linux Ubuntu 16.04
Hardware: PC
Customization: none

Configure command line:
`./configure`
(default build)

### Bug description

httpIsAuthenticated(), returns false although login is successful.

#### How to reproduce the issue

1. Compile and run **login-database** sample
2. Login with joshua/pass1

#### Expected behavior
- login successful, redirect to index page
- **commonBase function is called, httpIsAuthenticated() returns true**

#### Behavior
- login successful, redirect to index
- **commonBase function is called, httpIsAuthenticated() returns false, redirect to login page**

### Additional info
From my debugging, it seems that even though username sessionVar is set in httpLogin(), when retrieving the username, it returns NULL.

If I can help you with additional information, please let me know.

Thank you,
Cristian

**Comment by dev-embedthis** [comment]
We've tested this and it is operating correctly for us.

The common base is first called when trying to login. This time, it returns false because you are not yet logged in. Then the login occurs and a redirect to index.esp. Then it is called for that request and it returns true because you are logged in.

The first request to login will return headers like:

```
set-cookie: esp-login_database=4::http.session::67f1e7cfdd2a0b15af731c388a6a52a7; path=/; domain=127.0.0.1; secure; httponly
```

This cookie is then returned when requesting the index.esp

```
cookie: esp-login_database=4::http.session::67f1e7cfdd2a0b15af731c388a6a52a7;
```
